
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/visual studio/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/visual studio/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/visual studio/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/visual studio/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
      生成启动时间为 2023/8/31 17:52:08。
      
      节点 1 上的项目“E:\\Projects\\GitProject\\myshrimp\\Pure\\MyShrimpApp\\CMakeFiles\\3.26.4-msvc4\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdC.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        正在对“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”执行 Touch 任务。
      ClCompile:
        D:\\visual studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        D:\\visual studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> E:\\Projects\\GitProject\\myshrimp\\Pure\\MyShrimpApp\\CMakeFiles\\3.26.4-msvc4\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=D:\\visual studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate”执行 Touch 任务。
      已完成生成项目“E:\\Projects\\GitProject\\myshrimp\\Pure\\MyShrimpApp\\CMakeFiles\\3.26.4-msvc4\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:00.80
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        E:/Projects/GitProject/myshrimp/Pure/MyShrimpApp/CMakeFiles/3.26.4-msvc4/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/visual studio/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/visual studio/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/visual studio/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
      生成启动时间为 2023/8/31 17:52:09。
      
      节点 1 上的项目“E:\\Projects\\GitProject\\myshrimp\\Pure\\MyShrimpApp\\CMakeFiles\\3.26.4-msvc4\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdCXX.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        正在对“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”执行 Touch 任务。
      ClCompile:
        D:\\visual studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        D:\\visual studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> E:\\Projects\\GitProject\\myshrimp\\Pure\\MyShrimpApp\\CMakeFiles\\3.26.4-msvc4\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=D:\\visual studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate”执行 Touch 任务。
      已完成生成项目“E:\\Projects\\GitProject\\myshrimp\\Pure\\MyShrimpApp\\CMakeFiles\\3.26.4-msvc4\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:00.59
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        E:/Projects/GitProject/myshrimp/Pure/MyShrimpApp/CMakeFiles/3.26.4-msvc4/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/visual studio/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/visual studio/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "E:/Projects/GitProject/myshrimp/Pure/MyShrimpApp/CMakeFiles/CMakeScratch/TryCompile-xv7zek"
      binary: "E:/Projects/GitProject/myshrimp/Pure/MyShrimpApp/CMakeFiles/CMakeScratch/TryCompile-xv7zek"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: E:/Projects/GitProject/myshrimp/Pure/MyShrimpApp/CMakeFiles/CMakeScratch/TryCompile-xv7zek
        
        Run Build Command(s):D:/visual studio/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_bffea.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && 适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
        生成启动时间为 2023/8/31 17:52:09。
        
        节点 1 上的项目“E:\\Projects\\GitProject\\myshrimp\\Pure\\MyShrimpApp\\CMakeFiles\\CMakeScratch\\TryCompile-xv7zek\\cmTC_bffea.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_bffea.dir\\Debug\\”。
          正在创建目录“E:\\Projects\\GitProject\\myshrimp\\Pure\\MyShrimpApp\\CMakeFiles\\CMakeScratch\\TryCompile-xv7zek\\Debug\\”。
          正在创建目录“cmTC_bffea.dir\\Debug\\cmTC_bffea.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_bffea.dir\\Debug\\cmTC_bffea.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
          正在对“cmTC_bffea.dir\\Debug\\cmTC_bffea.tlog\\unsuccessfulbuild”执行 Touch 任务。
        ClCompile:
          D:\\visual studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_bffea.dir\\Debug\\\\" /Fd"cmTC_bffea.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "D:\\visual studio\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32822 for x64
          CMakeCCompilerABI.c
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_bffea.dir\\Debug\\\\" /Fd"cmTC_bffea.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "D:\\visual studio\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
        Link:
          D:\\visual studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\Projects\\GitProject\\myshrimp\\Pure\\MyShrimpApp\\CMakeFiles\\CMakeScratch\\TryCompile-xv7zek\\Debug\\cmTC_bffea.exe" /INCREMENTAL /ILK:"cmTC_bffea.dir\\Debug\\cmTC_bffea.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/Projects/GitProject/myshrimp/Pure/MyShrimpApp/CMakeFiles/CMakeScratch/TryCompile-xv7zek/Debug/cmTC_bffea.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/Projects/GitProject/myshrimp/Pure/MyShrimpApp/CMakeFiles/CMakeScratch/TryCompile-xv7zek/Debug/cmTC_bffea.lib" /MACHINE:X64  /machine:x64 cmTC_bffea.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_bffea.vcxproj -> E:\\Projects\\GitProject\\myshrimp\\Pure\\MyShrimpApp\\CMakeFiles\\CMakeScratch\\TryCompile-xv7zek\\Debug\\cmTC_bffea.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_bffea.dir\\Debug\\cmTC_bffea.tlog\\unsuccessfulbuild”。
          正在对“cmTC_bffea.dir\\Debug\\cmTC_bffea.tlog\\cmTC_bffea.lastbuildstate”执行 Touch 任务。
        已完成生成项目“E:\\Projects\\GitProject\\myshrimp\\Pure\\MyShrimpApp\\CMakeFiles\\CMakeScratch\\TryCompile-xv7zek\\cmTC_bffea.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:00.72
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/visual studio/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/visual studio/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "E:/Projects/GitProject/myshrimp/Pure/MyShrimpApp/CMakeFiles/CMakeScratch/TryCompile-u5cyan"
      binary: "E:/Projects/GitProject/myshrimp/Pure/MyShrimpApp/CMakeFiles/CMakeScratch/TryCompile-u5cyan"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: E:/Projects/GitProject/myshrimp/Pure/MyShrimpApp/CMakeFiles/CMakeScratch/TryCompile-u5cyan
        
        Run Build Command(s):D:/visual studio/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_c3e7e.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && 适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
        生成启动时间为 2023/8/31 17:52:10。
        
        节点 1 上的项目“E:\\Projects\\GitProject\\myshrimp\\Pure\\MyShrimpApp\\CMakeFiles\\CMakeScratch\\TryCompile-u5cyan\\cmTC_c3e7e.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_c3e7e.dir\\Debug\\”。
          正在创建目录“E:\\Projects\\GitProject\\myshrimp\\Pure\\MyShrimpApp\\CMakeFiles\\CMakeScratch\\TryCompile-u5cyan\\Debug\\”。
          正在创建目录“cmTC_c3e7e.dir\\Debug\\cmTC_c3e7e.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_c3e7e.dir\\Debug\\cmTC_c3e7e.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
          正在对“cmTC_c3e7e.dir\\Debug\\cmTC_c3e7e.tlog\\unsuccessfulbuild”执行 Touch 任务。
        ClCompile:
          D:\\visual studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_c3e7e.dir\\Debug\\\\" /Fd"cmTC_c3e7e.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "D:\\visual studio\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32822 for x64
          CMakeCXXCompilerABI.cpp
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_c3e7e.dir\\Debug\\\\" /Fd"cmTC_c3e7e.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "D:\\visual studio\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          D:\\visual studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\Projects\\GitProject\\myshrimp\\Pure\\MyShrimpApp\\CMakeFiles\\CMakeScratch\\TryCompile-u5cyan\\Debug\\cmTC_c3e7e.exe" /INCREMENTAL /ILK:"cmTC_c3e7e.dir\\Debug\\cmTC_c3e7e.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/Projects/GitProject/myshrimp/Pure/MyShrimpApp/CMakeFiles/CMakeScratch/TryCompile-u5cyan/Debug/cmTC_c3e7e.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/Projects/GitProject/myshrimp/Pure/MyShrimpApp/CMakeFiles/CMakeScratch/TryCompile-u5cyan/Debug/cmTC_c3e7e.lib" /MACHINE:X64  /machine:x64 cmTC_c3e7e.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_c3e7e.vcxproj -> E:\\Projects\\GitProject\\myshrimp\\Pure\\MyShrimpApp\\CMakeFiles\\CMakeScratch\\TryCompile-u5cyan\\Debug\\cmTC_c3e7e.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_c3e7e.dir\\Debug\\cmTC_c3e7e.tlog\\unsuccessfulbuild”。
          正在对“cmTC_c3e7e.dir\\Debug\\cmTC_c3e7e.tlog\\cmTC_c3e7e.lastbuildstate”执行 Touch 任务。
        已完成生成项目“E:\\Projects\\GitProject\\myshrimp\\Pure\\MyShrimpApp\\CMakeFiles\\CMakeScratch\\TryCompile-u5cyan\\cmTC_c3e7e.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:00.69
        
      exitCode: 0
...
